import * as yup from 'yup';

export const tierValidationSchema = yup.object().shape({
  price: yup.number().required(),
  tier_level: yup.number().integer().required(),
  description: yup.string().nullable(),
  max_messages: yup.number().integer().nullable(),
  tier_name: yup.string().required(),
  tier_duration: yup.number().integer().nullable(),
  tier_status: yup.boolean().nullable(),
  tier_expiration_notification: yup.boolean().nullable(),
  tier_discount: yup.number().nullable(),
  tier_upgrade_option: yup.boolean().nullable(),
  tier_renewal_option: yup.boolean().nullable(),
  tier_auto_upgrade: yup.boolean().nullable(),
  tier_downgrade_option: yup.boolean().nullable(),
  tier_cancellation_option: yup.boolean().nullable(),
  tier_limit_per_user: yup.number().integer().nullable(),
  tier_max_users: yup.number().integer().nullable(),
  tier_additional_features: yup.string().nullable(),
  tier_trial_period: yup.number().integer().nullable(),
  tier_activation_date: yup.date().nullable(),
  tier_deactivation_date: yup.date().nullable(),
  tier_customization_option: yup.boolean().nullable(),
  tier_support_option: yup.boolean().nullable(),
  tier_referral_bonus: yup.number().nullable(),
  tier_feedback_option: yup.boolean().nullable(),
  tier_partner_discount: yup.number().nullable(),
  tier_reward_points: yup.number().integer().nullable(),
});
